### ISSUE TITLE
Add Call-To-Action button to landing page

### ISSUE THREAD

**Issue by BrandonArmand** [BrandonArmand/Binari#14]
- [ ] Bug
- [ ] Clean up
- [ ] Question
- [x] Enhancement
- [ ] Suggestion
- [ ] Other
 
## What needs to be done.
Include a new simple button under the header that will route to the playground.

## Why
Something simple for the user to quickly get started with their coding.

## How
Use react-router and the material Ui button component that routes to the playground. Make the button pop and stand-out.

**Comment by ghost** [comment]
What about fixing the compile warning like a title missing from an iframe on ProductSection.js?
Is that useful?  Then do a pull request?

**Comment by BrandonArmand** [comment]
> What about fixing the compile warning like a title missing from an iframe on ProductSection.js?
> Is that useful? Then do a pull request?

Absolutely, you are welcome to do a PR on anything you think should be done.

**Comment by BrandonArmand** [comment]
> What about fixing the compile warning like a title missing from an iframe on ProductSection.js?
> Is that useful? Then do a pull request?

In fact, since you seem to be new to open source contribution, go ahead and create an issue using the template, then once you are ready to create a pull request, reference the issue that you created (: 

Good luck!

**Comment by maciejblawat** [comment]
Hello.I would like to work on this issue if its possible.But where should I place this button i which file ?

**Comment by BrandonArmand** [comment]
@Lucyferos someone already claimed this; however, you are more than welcome to do more than just create the button (: for instance, on the landing page, there is some text that says "Gayle Laakmann McDowell", which was the old video author. If you would like, you can update the text to explain briefly what the current video is about. This has been something that I have been wanting to get done, but haven't gotten around to doing.

**Comment by maciejblawat** [comment]
Ok I can try but which file contains text from home page ?

**Comment by maciejblawat** [comment]
Okay nevermind i found it.
