### ISSUE TITLE
Replace Landing page video

### ISSUE THREAD

**Issue by BrandonArmand** [BrandonArmand/Binari#15]
- [ ] Bug
- [ ] Clean up
- [ ] Question
- [ ] Enhancement
- [ ] Suggestion
- [x] Other
 
## What needs to be done.
Find a better video related to binary trees

## Why
Seems more appropriate

## How
A video of a mock or real interview based on binary trees sounds like the best option.

**Comment by gooseNjuice** [comment]
I did it.
