### ISSUE TITLE
Create Hotkeys

### ISSUE THREAD

**Issue by BrandonArmand** [BrandonArmand/Binari#19]
- [ ] Bug
- [ ] Clean up
- [ ] Question
- [x] Enhancement
- [ ] Suggestion
- [ ] Other
 
## What needs to be done.
Implement hotkeys for the code editor.

## Why
It will allow for a better user-flow.

## How
Start with the basic VSCode hotkeys, and expand from there.

#### Starting point:
- [x] Run Code  (CTR + ENTER)
- [x] Reset
- [x] Beautify
- [x] Autofill suggestions
- [x] Comment selection

**Comment by PathakPratik** [comment]
https://github.com/jaywcjlove/hotkeys
This library looks helpful which also has React bindings. Going ahead with this task.

**Comment by BrandonArmand** [comment]
@PathakPratik Weirdly enough, I never saw this comment. I would love to see if you made any progress, if not, I would love to know if you are still interested in taking this task. It sounds great :)

**Comment by Ethan-Pongon** [comment]
@BrandonArmand Hey I'd like to contribute for this, is it okay to just try to get one of the hotkeys working then make a pull request? I've never done this before so I'm not familiar with the rules.
