### ISSUE TITLE
Add Color Scheme to Directory

### ISSUE THREAD

**Issue by BrandonArmand** [BrandonArmand/Binari#24]
- [ ] Bug
- [ ] Clean up
- [ ] Question
- [x] Enhancement
- [ ] Suggestion
- [ ] Other
 
## What needs to be done.
Add a square box to the right side of a lesson within the directory, in the future it will represent the difficulty of the lesson.

## Why
So that the user knows what they are getting themselves into.

## How
- For added the color, just edit the `<li>`
- For the conditional coloring, add a difficulty value in the lesson object and include that within the `<li>` rendering.

**Comment by alti21** [comment]
Can I work on this?

**Comment by BrandonArmand** [comment]
Absolutely

**Comment by alti21** [comment]
#34
