### ISSUE TITLE
There  is a grammatical mistake  in chapter one(insertion)

### ISSUE THREAD

**Issue by technophile-04** [BrandonArmand/Binari#70]
# Grammatica mistake in chapter one(insertion)
### In bullet number 4 i.e
* This process is repeated until the we reach to a leaf node(i.e. node with no child).
### This should be
*  This process is repeated until ~~the~~ we reach to a leaf node(i.e. node with no child).

**Comment by technophile-04** [comment]
Can I please fix this issue

**Comment by BrandonArmand** [comment]
Sure (: @technophile-04

**Comment by technophile-04** [comment]
Thanks, you so much @BrandonArmand it's my first contribution hope it gets merged
